# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

matrix:
  include:
    - os: debian
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6
        - CC=gcc=6
        - CXX=g++-6
        
env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
